### ISSUE TITLE
Can i help ? 

### ISSUE THREAD

**Issue by Decapitater** [cup-lang/cup#6]
its weird as its my first time to see someone develop a programming language , but hey i like the idea and i would love to support it reach me out here or telegram (same name) . 
Hoping for a good reply , @jgrajewsky

**Comment by jgrajewsky** [comment]
Thank you. I'm afraid right now you can only support the project by [becoming a Sponsor](https://github.com/sponsors/cup-lang) because it's still in very early development.

**Comment by Decapitater** [comment]
Alright so no coding development for now needed , got it
